# Generated by Django 3.0.5 on 2020-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('userFirst', models.TextField(blank=True)),
                ('userLast', models.TextField(blank=True)),
                ('donators', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('currentAmount', models.IntegerField()),
                ('daysActive', models.IntegerField()),
                ('status', models.BooleanField(blank=True)),
                ('imageUrl', models.TextField(blank=True)),
                ('launchDate', models.TextField(blank=True)),
                ('campaignHearts', models.IntegerField(blank=True)),
                ('socialShareTotal', models.IntegerField(blank=True)),
                ('percentComplete', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentCompleteForGivenDays', models.DecimalField(decimal_places=2, max_digits=7)),
                ('moneyPerDonor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quality', models.TextField()),
            ],
        ),
    ]
