# Generated by Django 3.0.5 on 2020-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200407_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaignHearts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='currentAmount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daysActive',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='donators',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='moneyPerDonor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='percentComplete',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='percentCompleteForGivenDays',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='socialShareTotal',
            field=models.TextField(blank=True),
        ),
    ]
