# Generated by Django 3.0.5 on 2020-04-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200407_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('goal', models.TextField()),
                ('daysActive', models.TextField()),
                ('hasBeneficiary', models.BooleanField()),
                ('isCharity', models.BooleanField()),
                ('visibleInSearch', models.BooleanField()),
            ],
        ),
    ]
