# Generated by Django 3.0.5 on 2020-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hasBeneficiary',
            field=models.TextField(blank=True, default='FALSE'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='locationCity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='locationCountry',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='quality',
            field=models.TextField(blank=True),
        ),
    ]
