# Generated by Django 3.0.5 on 2020-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200408_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
