# Generated by Django 3.0.5 on 2020-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_predict_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='locationState',
            field=models.TextField(blank=True),
        ),
    ]
